version: '3.8'

services:
  backend:
    image: ${REGISTRY}/${BACKEND_IMAGE}:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - pingaroo-network

  frontend:
    image: ${REGISTRY}/${FRONTEND_IMAGE}:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pingaroo-network

networks:
  pingaroo-network:
    driver: bridge 